[build]
  command = "cd learnify-content-helper-main && npm install --legacy-peer-deps && npm run build"
  publish = "learnify-content-helper-main/dist"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18= "--legacy-peer-deps --force"
